### ISSUE TITLE
Issue handling val assignment to function return

### ISSUE THREAD

**Issue by bms-1984** [bms-1984/orwell#1]
`fun square(a) { a * a }
val a = square(2)`

The above code should set the value of `a` to `4`. Instead, it produces an exception when reached in `IRVisitor::visit(ValNode)`:

`Exception in thread "main" java.lang.ClassCastException: me.tomassetti.kllvm.LocalValueRef cannot be cast to me.tomassetti.kllvm.FloatConst
        at net.bms.orwell.tree.IRVisitor.visit(IRVisitor.kt:51)
        at net.bms.orwell.tree.IRVisitor.visit(IRVisitor.kt:14)
        at net.bms.orwell.OrwellKt.runOrwell(Orwell.kt:94)
        at net.bms.orwell.OrwellKt.access$runOrwell(Orwell.kt:1)
        at net.bms.orwell.OrwellKt$main$2$1.invoke(Orwell.kt:34)
        at net.bms.orwell.OrwellKt$main$2$1.invoke(Orwell.kt)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:154)
        at net.bms.orwell.OrwellKt.main(Orwell.kt:32)`

This has to do with the handling of values returned from `IRVisitor::visit(FunCallNode)` and shouldn't require much overhauling.

**Comment by bms-1984** [comment]
This issue is fixed in `3a7487c02fd3adc7726034aa70a2d2fcecb1afca`.

It was caused by my insistence on creating a global variable in LLVM for each value. This was unnecessary, since identifiers are resolved at compile time.
